export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_PROFILE = 'LOGIN_PROFILE';
export const LOG_OUT = 'LOG_OUT';

export const HOME_VIDEOS_REQUEST = 'HOME_VIDEOS_REQUEST';
export const HOME_VIDEOS_SUCCESS = 'HOME_VIDEOS_SUCCESS';
export const HOME_VIDEOS_FAIL = 'HOME_VIDEOS_FAIL'

export const SELECTED_VIDEO_REQUEST = 'SELECTED_VIDEO_REQUEST';
export const SELECTED_VIDEO_SUCCESS = 'SELECTED_VIDEO_SUCCESS';
export const SELECTED_VIDEO_FAIL = 'SELECTED_VIDEO_FAIL';

export const GET_CHANNEL_REQUEST = 'GET_CHANNEL_REQUEST';
export const GET_CHANNEL_SUCCESS = 'GET_CHANNEL_SUCCESS';
export const GET_CHANNEL_FAIL = 'GET_CHANNEL_FAIL';

export const GET_SUBSCRIPTION_STATUS = 'GET_SUBSCRIPTION_STATUS';

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL';

export const ADD_COMMENT = 'ADD_COMMENT';

export const RELATED_VIDEOS_REQUEST = 'RELATED_VIDEOS_REQUEST';
export const RELATED_VIDEOS_SUCCESS = 'RELATED_VIDEOS_SUCCESS';
export const RELATED_VIDEOS_FAIL = 'RELATED_VIDEOS_FAIL';

export const SEARCH_VIDEOS_REQUEST = 'SEARCH_VIDEOS_REQUEST'
export const  SEARCH_VIDEOS_SUCCESS = 'SEARCH_VIDEOS_SUCCESS';
export const SEARCH_VIDEOS_FAIL = 'SEARCH_VIDEOS_FAIL';

export const SUBSCRIBED_CHANNELS_REQUEST = 'SUBSCRIBED_CHANNELS_REQUEST'
export const SUBSCRIBED_CHANNELS_SUCCESS = 'SUBSCRIBED_CHANNELS_SUCCESS';
export const SUBSCRIBED_CHANNELS_FAIL = 'SUBSCRIBED_CHANNELS_FAIL';

export const CHANNEL_VIDEOS_REQUEST = 'CHANNEL_VIDEOS_REQUEST'
export const CHANNEL_VIDEOS_SUCCESS = 'CHANNEL_VIDEOS_SUCCESS';
export const CHANNEL_VIDEOS_FAIL = 'CHANNEL_VIDEOS_FAIL';

